### ISSUE TITLE
Super nitpicky issue

### ISSUE THREAD

**Issue by Lovebird-Connoisseur** [pbv/haskelite#2]
Olá! Recentemente descobri um "gafe" na documentação, mais especificamente [aqui](https://github.com/pbv/haskelite?tab=readme-ov-file#language-features).

Onde está escrito "supporte" em vez de "supported".

Atendendo à gravidade do bug ainda considerei fazer uma pull request, apenas não o fazendo por questões de força maior (i.e. (ainda) não o sei fazer :) ).

**Comment by pbv** [comment]
Obrigado!
